### ISSUE TITLE
about test_testnet.py https://prsdigg.com/articles/4375be62-6ef4-4de2-af9a-086816380fde

### ISSUE THREAD

**Issue by ShallMate** [learnforpractice/mixin-python#2]
about test_testnet.py https://prsdigg.com/articles/4375be62-6ef4-4de2-af9a-086816380fde
Sorry to disturb you, I found in the test_testnet.py file that you are based on this blog. However, this blog requires digital currency to be purchased. It is not that I don’t want to pay, but I really don’t have experience in purchasing digital currency. Can you share my content about this blog? I think it can help me solve the problem I am facing now. Many problems. Thank you very much if you can.

**Comment by learnforpractice** [comment]
Use notebook to play with testnet as show in the following link.

https://github.com/learnforpractice/mixin-python#run-tests-in-jupyter-notebook <https://github.com/learnforpractice/mixin-python#run-tests-in-jupyter-notebook>


Also you can try it online:

https://mybinder.org/v2/gh/learnforpractice/mixin-python/HEAD?filepath=notebook%2Fhelloworld.ipynb <https://mybinder.org/v2/gh/learnforpractice/mixin-python/HEAD?filepath=notebook/helloworld.ipynb>

**Comment by learnforpractice** [comment]
Use the following command to run the test case in test_testnet.py

python3 -m pytest -s -x tests/test_testnet.py -k test_deposit
